### PR TITLE
Fix Field Migration

### LINKED ISSUE #162: [MC 1.20.1 - Forge] Class field does not get remapped inside the forge module
Hey,

in my project I noticed that for an example in the `LootTable` class the field `pools` is not remapped for the forge module.

```java
public class LootTable {
    // ...

    private final List<LootPool> f_79109_;   

    // ...
}
```

I'm using MC 1.20.1 right now with Forge 47.2.0 but I tested multiple Forge versions. I also tested it without parchment and the issue still exist (But tbf I don't know if parchment would even touch that). 
What I notice is that forge seems to patch the field. In Vanilla the field type is an array `LootPool[] pools`, while in forge it's a list.

### PR DESCRIPTION
**Pull request by shedaniel**
#162 is caused by SrgMerger dropping the migrated fields. The easiest and most reliable way to fix this is to apply the migration to both base and srg tiny, instead of only applying to the base and let SrgMerger merge the mappings.

The fix seems pretty reliable.

### CODE REVIEW

File: src/main/java/net/fabricmc/loom/configuration/providers/forge/FieldMigratedMappingConfiguration.java [hunk 1]
```diff
@@ -139,39 +130,46 @@ public void updateFieldMigration(Project project) throws IOException {
...
+		if (Files.notExists(tinyMappings) || Files.notExists(tinyMappingsWithSrg)) {
 			Table<String, String, String> fieldDescriptorMap = HashBasedTable.create();
 
 			for (Map.Entry<FieldMember, String> entry : migratedFields) {
 				fieldDescriptorMap.put(entry.getKey().owner, entry.getKey().field, entry.getValue());
 			}
 
-			MemoryMappingTree mappings = new MemoryMappingTree();
+			injectMigration(project, fieldDescriptorMap, rawTinyMappings, tinyMappings);
+			injectMigration(project, fieldDescriptorMap, rawTinyMappingsWithSrg, tinyMappingsWithSrg);
```
Comment (Juuxel) [inline src/main/java/net/fabricmc/loom/configuration/providers/forge/FieldMigratedMappingConfiguration.java:144]: Thanks for this, it makes applying the same thing to the Mojang-merged mappings much easier too

**Review by Juuxel — APPROVED** [review]
I trust you that it works, I don't understand the field migrator to begin with :ioa:
