### PR TITLE
Split Minecraft and Forge jars

### LINKED ISSUE #1: Gray Panorama
Things to try:
- Not to merge minecraft with forge jar, making them two distinct jars

### LINKED ISSUE #20: Project using architectury loom fails to run a forge game instance in 1.15.2
When running `Minecraft Client (:forge)`, the game fails to finish loading with the following error: 
> Forge (forge) has failed to load correctly

A full log is available here: https://gist.github.com/Trikzon/df7831a9ac55de6c62b140b8deb97a5b

When the mod is built, the built jar works in a non-dev environment.
This is the workspace I am using and getting the error with: https://github.com/trikzon/armor-visibility/tree/1.15.2

### PR DESCRIPTION
**Pull request by shedaniel**
Fix #1 
Fix #20

### CODE REVIEW

File: src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java [hunk 1]
```diff
@@ -444,35 +486,32 @@ public String side() {
...
+					OutputConsumerPath outputConsumerForge = new OutputConsumerPath.Builder(forgeOutput).build()) {
 			outputConsumer.addNonClassFiles(input);
 
-			remapper.readClassPath(libraries);
-			remapper.readInputs(input);
-			remapper.apply(outputConsumer);
+			InputTag mcTag = remapper.createInputTag();
+			InputTag forgeTag = remapper.createInputTag();
+			remapper.readInputs(mcTag, input);
+			remapper.readInputs(forgeTag, forgeJar, forgeUserdevJar);
```
Comment (Juuxel) [inline src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java]: Possibly readInputsAsync here? (Not sure how it affects the perf with only two calls though)

File: src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java [hunk 2]
```diff
@@ -126,6 +132,10 @@ public static void setupConfigurations(Project project) {
 		extendsFrom(Constants.Configurations.LOADER_DEPENDENCIES, Constants.Configurations.MINECRAFT_DEPENDENCIES, project);
 		extendsFrom(Constants.Configurations.MINECRAFT_NAMED, Constants.Configurations.LOADER_DEPENDENCIES, project);
 
+		if (project.getExtensions().getByType(LoomGradleExtension.class).isForge()) {
+			extendsFrom(Constants.Configurations.FORGE_NAMED, Constants.Configurations.LOADER_DEPENDENCIES, project);
```
Comment (Juuxel) [inline src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java]: Hm? This seems a bit odd and redundant since they're already on the classpath (`MINECRAFT_NAMED` extends from `LOADER_DEPENDENCIES` above)

Comment (shedaniel) [reply src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java]: I did it this way since loom does this for minecraftNamed as well, not sure why they do it this way.

Comment (Juuxel) [reply src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java]: Iirc minecraftNamed extends from loaderDeps since the deps were added to the minecraftDependencies before (which was added to minecraftNamed back then). Adding them to forgeNamed shouldn't be necessary at all imo.

Comment (Juuxel) [reply src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java]: Iirc minecraftNamed extends from loaderDeps since the deps were added to the minecraftDependencies before (which was added to minecraftNamed back then). Adding them to forgeNamed shouldn't be necessary at all imo.

Edit: bad internet go brrr

Comment (shedaniel) [reply src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java]: I think this is just easier this way, some stuff in loom depends on `LOADER_DEPENDENCIES`:
```java
Mercury m = new Mercury();
m.setGracefulClasspathChecks(true);

for (File file : project.getConfigurations().getByName(Constants.Configurations.LOADER_DEPENDENCIES).getFiles()) {
    m.getClassPath().add(file.toPath());
}
```

Comment (Juuxel) [reply src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java]: This doesn't apply there. `extendsFrom(forgeNamed, loaderDependencies, project)` means that loader deps are included in forge named, not the other way around.

Comment (shedaniel) [reply src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java]: Oh, makes sense then

**Review by Juuxel — APPROVED** [review]
